version: '3.9'

services:
  pgadmin:
    container_name: pgadmin
    env_file: ${ENV_FILE}
    restart: always
    image: dpage/pgadmin4:latest
    volumes:
      - /backups:/backups
    ports: 
      - ${PGADMIN_PORT}:80
    networks:
      - ergopad-net

  flower:  
    container_name: flower
    env_file: ${ENV_FILE}
    restart: always
    image: mher/flower
    ports: 
      - ${FLOWER_PORT}:${FLOWER_PORT}
    command: celery --broker=redis://redis:${REDIS_PORT}/0 flower --port=${FLOWER_PORT}
    networks:
      - ergopad-net

networks:
  ergopad-net:
    external: true
